package net.mpimedia.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
@Entity
@Table(name = "position")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Position extends BaseEntity implements Serializable {
	/**
	* 
	*/
	private static final long serialVersionUID = -6915469135513082491L;
	@Column
	public String name;
	@Column
	public String description;

}
